### ISSUE TITLE
Design & Optimize URL structures

### ISSUE THREAD

**Issue by LinHeLurking** [GKDRateIt/back-end#3]
How would our resources be located?

A maybe good proposal:
(Bellowing, I use `<domain>` as a placeholder of RateIt domain) 

- `<domain>/`: Project Main Page
- `<domain>/courses`: All Courses
- `<domain>/professors`: All professors
- `<domain>/students`: All Students
- `<domain>/errors`: Error pages
- And much more...

**Comment by LinHeLurking** [comment]
Some compliments:

- `<domain>/resources/xxx`: store resources file, including HTML, JS, images, etc.
- `<domain>/api/xxx`: a web api call, which gets json response.

We only design page HTML/JS  patterns and store them in `/resources`. All "real" contents (such as students profiles, course details) should be fetched via `/api`. Then JS writes fetched contents back into pages. By this approch, we could keep all contents safe & secret, by acquiring authentication for `/api`.

**Comment by karuboniru** [comment]
Just serve static content (`Html/CSS/JS`) and dynamic contents (apis) from different domain? That we could serve them from different servers easier. (e.g. Use CF/GitHub Pages/OSS to serve htmls and use our own server to provide APIs)

**Comment by LinHeLurking** [comment]
> Just serve static content (`Html/CSS/JS`) and dynamic contents (apis) from different domain? That we could serve them from different servers easier. (e.g. Use CF/GitHub Pages/OSS to serve htmls and use our own server to provide APIs)

Good idea! Then we only need build our server for dynamic contents, leaving all resources files for buying & paying.
